[project]
name = "ml-semana1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Leny Tacuri", email = "lenytacuri1995@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.3",
    "seaborn>=0.12",
]

[project.scripts]
ml-semana1 = "ml_semana1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
]
